SELECT
    ISSUE_ID,
    ISSUE_NUMBER,
    REPOSITORY,
    COUNT(REPOSITORY) OVER(PARTITION BY REPOSITORY) AS COUNT_REPOSITORY,
    TITLE,
    BODY,
    STATE,
    STATE_REASON,
    COMMENTS_COUNT,
    AUTHOR_ID,
    AUTHOR_LOGIN,
    CREATED_AT,
    UPDATED_AT,
    CLOSED_AT,
    INGESTED_AT
FROM {{ ref("stg_git_raw") }}


SELECT
    REPOSITORY,
    COUNT(*) COUNT_REPO
FROM {{ ref("stg_git_raw") }}
GROUP BY REPOSITORY