SELECT 
    AUTHOR_ID,
    AUTHOR_LOGIN
FROM {{ ref("int_git_issues")}}
WHERE AUTHOR_ID IS NOT NULL AND AUTHOR_LOGIN IS NOT NULL
QUALIFY ROW_NUMBER() OVER(PARTITION BY AUTHOR_ID ORDER BY UPDATED_AT DESC) = 1